---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: password-generator-ingress
spec:
  tls:
    - hosts:
        - rest.localhost
  rules:
    - host: rest.localhost
      http:
        paths:
          - pathType: Prefix
            path: "/api/v1"
            backend:
              service:
                name: password-generator-service
                port:
                  number: 80
          - pathType: Prefix
            path: "/api/v2"
            backend:
              service:
                name: password-generator-service
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: password-generator-service
spec:
  selector:
    app: password-generator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-generator-deployment
  labels:
    app: password-generator
spec:
  #replicas: 2
  selector:
    matchLabels:
      app: password-generator
  template:
    metadata:
      labels:
        app: password-generator
    spec:
      containers:
        - image: jparker1121/pwdgen
          name: password-generator
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: default
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 10
---
